### ISSUE TITLE
Structure of MULTIPOINT geometry type in the console output

### ISSUE THREAD

**Issue by tibbles-and-tribbles** [geocompx/geocompr#1008]
For me, the output in the console for a MULTIPOINT geometry type is as follows...

```
multipoint <- rbind(c(5, 2), c(1, 3), c(3, 4), c(3, 2))
st_multipoint(multipoint)
```
Output from console in RStudio:
```
MULTIPOINT ((5 2), (1 3), (3 4), (3 2))
```

However, in the book, I see `MULTIPOINT (5 2, 1 3, 3 4, 3 2)` listed in section 2.2.4 above Figure 2.9 (https://r.geocompx.org/spatial-class#geometry)

In section 2.2.6, when creating a GEOMETRYCOLLECTION object in the code block labeled `02-spatial-data-24`, the MULTIPOINT component is again listed as `MULTIPOINT (5 2, 1 3, 3 4, 3 2)` (https://r.geocompx.org/spatial-class#sfg)

**Comment by tibbles-and-tribbles** [comment]
It's not an important issue, but I was thinking that the parentheses were a visual cue that the coordinates are stand-alone points and not points that are connected, as they are in a LINESTRING.

**Comment by Nowosad** [comment]
Interesting. It seems that both are possible, but I do not know why -- see https://r.geocompx.org/spatial-class#sfg:

![image](https://github.com/geocompx/geocompr/assets/3457131/02f6d017-c9e1-4312-9a88-5245765d58cb)

![image](https://github.com/geocompx/geocompr/assets/3457131/333a4414-2f55-4fb5-8e96-f14218714424)

**Comment by Robinlovelace** [comment]
I think the Simple Features spec is for the option without nested brackets. Bug/quirk in sf?

**Comment by Robinlovelace** [comment]
Seems both are allowed: 

![image](https://github.com/geocompx/geocompr/assets/1825120/a7ba7bef-8c3d-431a-b9c5-c469c87dc1e3)

https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry#Geometric_objects

**Comment by Nowosad** [comment]
👍🏻 good investigative work
