### ISSUE TITLE
grain raster object modified

### ISSUE THREAD

**Issue by tibbles-and-tribbles** [geocompx/geocompr#1012]
This is a very small issue.

In 3.3 "Manipulating raster objects" (https://r.geocompx.org/attr#manipulating-raster-objects), the following code block modifies the SpatRaster `grain` object. 

```
levels(grain) = data.frame(value = c(0, 1, 2), wetness = c("wet", "moist", "dry"))
levels(grain)
#> [[1]]
#>   value wetness
#> 1     0     wet
#> 2     1   moist
#> 3     2     dry
```

Later, in 3.3.2, `grain` is passed to `freq()`

```
freq(grain)
#>   layer value count
#> 1     1  clay    10
#> 2     1  silt    13
#> 3     1  sand    13
```

However, the output does not reflect the changes made to the `grain` object. 

Like I said, a small issue.

**Comment by Nowosad** [comment]
Thanks! Fixed: https://github.com/geocompx/geocompr/commit/0a421ff70b8dab302660dba8b6cf9d762d26a2fa
