### ISSUE TITLE
line_sfc object not used in any relationship queries

### ISSUE THREAD

**Issue by tibbles-and-tribbles** [geocompx/geocompr#1017]
In 4.2.2 (https://r.geocompx.org/spatial-operations#topological-relations), the object `line_sfc` is created but not used for any relationship queries (at least not in 4.2.2 or 4.2.3). The line is plotted in Figure 4.3, but I don't know why. 

```
line_sfc = st_sfc(st_linestring(cbind(
  x = c(0.4, 1),
  y = c(0.2, 0.5)
)))
# create points
point_df = data.frame(
  x = c(0.2, 0.7, 0.4),
  y = c(0.1, 0.2, 0.8)
)
point_sf = st_as_sf(point_df, coords = c("x", "y"))
```

**Comment by Robinlovelace** [comment]
Agreed, we should probably look to use it. Any thoughts on how welcome.

**Comment by tibbles-and-tribbles** [comment]
I thought the section worked pretty well without using the line segment; perhaps use a line segment in one of the exercises at the end of Chapter 4. But instead of using the line segment depicted in Figure 4.3, use a highway that intersects multiple states from the `tigris` package. I’m going to practice spatial subsetting and spatial joining using geometries from the tigris package today. I’ll let you know what I come up with.

**Comment by tibbles-and-tribbles** [comment]
I experimented with the geometries for major US highways from the tigris package. It did not work out as I had planned. First, the highways are broken up into segments, so they need to be aggregated. Which is fine, except that there’s often missing pieces of highway, probably because the names of highways can change from place to place (or maybe the data is just missing). Suffice it to say, extracting the geometry for a specific highway that crosses multiple US states would require some research. I didn’t have the time to do that this morning, so I was not able to come up with a nice, clean example of using a linestring (a highway) to query a data set of polygons (states). Maybe there are data sets for highways in other countries that are easier to work with.

**Comment by Robinlovelace** [comment]
Simple solution :+1:
