### ISSUE TITLE
Legends overlap objects in Figure 9.6

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompr#1020]
This was a comment from the final round of reviewer comments:

> the legends overlap the map figures in Figure 9.6. This should be fixed. It is also
present, to a lesser extent, in Figure 9.11.

Having had a quick look, I agree they could be better:

![image](https://github.com/geocompx/geocompr/assets/1825120/b2cc410e-a343-40ae-86e8-f43fe6a12e5c)

Link in the book: https://r.geocompx.org/adv-map#fig:break-styles

**Comment by Nowosad** [comment]
![image](https://github.com/geocompx/geocompr/assets/3457131/05a598fb-40bc-4930-a688-56a54feae062)

**Comment by Nowosad** [comment]
Done

**Comment by Robinlovelace** [comment]
:fire:
