### ISSUE TITLE
Additional information about Table 5.1 regarding geometry conversions might be needed

### ISSUE THREAD

**Issue by tibbles-and-tribbles** [geocompx/geocompr#1036]
In subsection 5.2.8 (https://r.geocompx.org/geometry-operations#type-trans), I think that Table 5.1 could use some additional information explaining the origin of the table cell values. These cell values represent the number of features generated by the corresponding conversion, right? But how do we know the number of coordinates in the original geometry?

**Comment by Nowosad** [comment]
Hi @tibbles-and-tribbles -- thanks for your comments. This part was heavily trimmed in the past. You can find some extended code at https://github.com/geocompx/geocompx.org/blob/main/post/wip/casting-geometries-extended.Rmd_. Do you have any suggestions how to make it better?

**Comment by tibbles-and-tribbles** [comment]
And, by the way, thanks for including so much detail in the book. Creating a table like this must be a lot of work, so I appreciate it!

**Comment by Nowosad** [comment]
That is the working link: <https://github.com/geocompx/geocompx.org/blob/main/post/wip/casting-geometries-extended.Rmd_>

Thanks for the suggestions -- I will try to work on them in the next few days.

**Comment by Nowosad** [comment]
https://github.com/geocompx/geocompr/pull/1040
