### ISSUE TITLE
Add formula for resolution to Chapter 5

### ISSUE THREAD

**Issue by tibbles-and-tribbles** [geocompx/geocompr#1041]
In subsection [5.3.3 "Aggregation and Disaggregation"](https://r.geocompx.org/geometry-operations#aggregation-and-disaggregation), perhaps readers might benefit from a review of the formula for resolution.

$\displaystyle \text{resolution} = \Big(\frac{\text{xmax} - \text{xmin}}{\text{ncol}}, \frac{\text{ymax} - \text{ymin}}{\text{nrow}}\Big)$

And then state that "decreasing" the resolution with `aggregate()` actually increases the component values of the resolution listed in the raster header.

**Comment by tibbles-and-tribbles** [comment]
While reading 5.3.3, I took the following notes to resolve the issue I was having with the resolution:

***

Let's review the changes from `dem` to `dem_lower`:

| object | resolution | grid | extent |
| ---- | ---- | ---- | ---- |
| `dem` | $(30.85, 30.85)$ | $117 \times 117$ | $794599.1, 798208.6, 8931775, 8935384$ |
| `dem_lower` | $(154.25, 154.25)$ | $24 \times 24$ | $794599.1, 798301.1, 8931682, 8935384$ |

Notice that "decreasing" the resolution with `aggregate()` actually increases the component values of the resolution in the raster header from $(30.85, 30.85)$ to $(154.25, 154.25)$. This is counterintuitive, but it helps to the review the formula for the resolution per the raster data model.

$\displaystyle \text{resolution} = \Big(\frac{\text{xmax} - \text{xmin}}{\text{ncol}}, \frac{\text{ymax} - \text{ymin}}{\text{nrow}}\Big)$

`aggregate()` "decreased" the resolution by decreasing the grid size, that is, by decreasing the number of rows (`nrow`) and columns (`ncol`). The extent was slightly adjusted probably to accommodate the new grid size. Decreasing the number of rows and columns, in turn, actually increases the component values of the resolution per the formula.

***

**Comment by Nowosad** [comment]
@tibbles-and-tribbles thank you.

Please take a look at my changes at https://github.com/geocompx/geocompr/pull/1043. 

I move the equation to the second chapter (as it is a general concept), and added some of your explanation to the fifth chapter.
