### ISSUE TITLE
style argument for some tmap functions is deprecated

### ISSUE THREAD

**Issue by tibbles-and-tribbles** [geocompx/geocompr#1069]
In subsection 9.2.4 "Scales" (https://r.geocompx.org/adv-map#scales), the `style` argument for `tmap` functions is discussed. There's a list of possible values for `style`, but there's no code example. When I run my own code example, I get a deprecation warning.

```
tm_shape(nz) +
  tm_polygons(
    fill = "Median_income",
    style = "pretty"
  )
```
Output:
```
tm_polygons: Deprecated tmap v3 code detected. Code translated to v4
```
 But the `style` argument still works with functions like `tm_scale_intervals()`, so perhaps there's no issue here.

**Comment by tibbles-and-tribbles** [comment]
I should use the `style` argument with functions like `tm_scale_intervals()`, right? If so, disregard this issue.

**Comment by Nowosad** [comment]
`style` is an argument in the `tm_scale_intervals()` function:

``` r
library(spData)
library(tmap)
tm_shape(nz) +
  tm_polygons(
    fill = "Median_income",
    tm_scale_intervals(style = "jenks")
  )
```

![](https://i.imgur.com/DKkA1ou.png)

**Comment by Nowosad** [comment]
@tibbles-and-tribbles what do you think about this rewrite: https://github.com/geocompx/geocompr/pull/1070/files?

**Comment by tibbles-and-tribbles** [comment]
@Nowosad : yes that helps!

**Comment by Nowosad** [comment]
Thanks! I also think it is better now.
