### ISSUE TITLE
About contents

### ISSUE THREAD

**Issue by babayoshihiko** [geocompx/geocompr#1081]
01-introduction.Rmd
L. 76 (footnote #2): It does not seem that installation is covered in Chapter 2.

08-read-write-plot.Rmd:
L. 503 Czechia may be Czech Republic?

**Comment by Robinlovelace** [comment]
Agreed, these are good points.

**Comment by Robinlovelace** [comment]
Thanks @babayoshihiko please review #1082 which should fix those issues.
