### ISSUE TITLE
Reference error in text of section 2.2

### ISSUE THREAD

**Issue by darrellcarvalho** [geocompx/geocompr#1096]
Location: https://r.geocompx.org/spatial-class#vector-data
Error: in the portion discussing PROJ, text as written is (emphasis mine):

> [PROJ](https://proj.org/), a powerful library for coordinate system transformations, which underlies the content covered in Chapter [7](https://r.geocompx.org/reproj-geo-data#reproj-geo-data) ***and [7](https://r.geocompx.org/reproj-geo-data#reproj-geo-data)***

Not sure what other section it should be pointing to for the second reference, or I would pull and correct myself.

**Comment by Nowosad** [comment]
Thank you @darrellcarvalho !
