### ISSUE TITLE
Some maps are blurred

### ISSUE THREAD

**Issue by Nowosad** [geocompx/geocompr#1106]
E.g., https://r.geocompx.org/raster-vector#fig:vector-rasterization1

![image](https://github.com/geocompx/geocompr/assets/3457131/036b864a-334b-45d2-b8c5-4d05be4f588e)

Reported at https://github.com/r-tmap/tmap/issues/892

**Comment by Robinlovelace** [comment]
Good spot, should be fixed upstream now I guess. Will re-build and check..

**Comment by Nowosad** [comment]
![image](https://github.com/geocompx/geocompr/assets/3457131/7f012795-586e-49ce-92b4-53573c3edfdc)

**Comment by Robinlovelace** [comment]
:tada:
