### ISSUE TITLE
Render fails in the Eco chapter

### ISSUE THREAD

**Issue by Nowosad** [geocompx/geocompr#1108]
https://github.com/geocompx/geocompr/actions/runs/10140130082/job/28034711566

```
62/70 [15-eco-27]        
Error in `private$.get_values()`:
! attempt to apply non-function
Backtrace:
 1. autotuner_rf$predict(task)
 7. paradox (local) `<fn>`()
 8. paradox:::.__ParamSet__values(...)

Quitting from lines 532-534 [15-eco-27] (15-eco.Rmd)
```

@jannes-m -- can you take a look at it?

**Comment by jannes-m** [comment]
ok, thanks for letting me know, I'll have a look at it in the coming days

**Comment by jannes-m** [comment]
I fixed the problem in the eco-chapter. Now ci/cd works again execpt for the qgis run, where it compains  about missing libraries bslib and downlilt (see https://github.com/geocompx/geocompr/actions/runs/10206927124/job/28240752484), though I don't know why they are missing here but not in the other run. Any ideas?

**Comment by Robinlovelace** [comment]
Not sure but could it be because https://github.com/geocompx/geocompkg actions are failing?

**Comment by jannes-m** [comment]
Ah, well spotted, thanks!!
