### ISSUE TITLE
! Field/Binding is read-only (Actions failing)

### ISSUE THREAD

**Issue by Nowosad** [geocompx/geocompr#1111]
@jannes-m -- sorry for bothering you, but the GHA is failing in ch12: https://github.com/geocompx/geocompr/actions/runs/10936378995/job/30359901540. Could you take a look at it?

**Comment by jannes-m** [comment]
I am a bit baffled, running this in our docker container, the error is not occurring. The only difference for now is that I have used `remotes::install_github("mlr-org/mlr3extralearners@v0.9.0")`.

**Comment by jannes-m** [comment]
Looking at https://github.com/geocompx/geocompr/blob/main/.github/workflows/main.yaml (here, we install geocompkg), I would suggest to use `remotes::install_github("mlr-org/mlr3extralearners@v0.9.0")` there also for the moment.

**Comment by Robinlovelace** [comment]
Should probably keep this open until the non-evaluated chunks are evaluated again.

See here for the changes, some of which may no longer be necessary after https://github.com/geocompx/geocompkg/pull/45 was merged:

https://github.com/geocompx/geocompr/pull/1117/files
