### ISSUE TITLE
Confusing answer for Chapter 7 Exercise 2

### ISSUE THREAD

**Issue by dhersz** [geocompx/geocompr#529]
![image](https://user-images.githubusercontent.com/1557047/80417461-2d100b00-88ac-11ea-9322-bc5d5f8df2cd.png)

[Link](https://geocompr.github.io/geocompkg/articles/solutions07.html) for exercise solutions.

I guess it was meant to be:

`read_sf()` prints outputs and keeps strings as text strings (`st_read()` creates factors).

**Comment by Robinlovelace** [comment]
Thanks for flagging this @dhersz. I think the answer may change with R 4.0.0.

**Comment by Nowosad** [comment]
@Robinlovelace can you improve the first two exercises (and their answers) for ch8 (https://github.com/Robinlovelace/geocompr/blob/main/_08-ex.Rmd)?

**Comment by Nowosad** [comment]
Post-meeting reminder: @Robinlovelace

**Comment by Robinlovelace** [comment]
On the todo list.

**Comment by Robinlovelace** [comment]
Belated update on this @dhersz, fixed in the commit above, sorry it took so long!
