### ISSUE TITLE
Mention 'dynamic CRSs'

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompr#739]
Context: this from @agila5: https://twitter.com/a_gilardi5/status/1487813588454678528 

I have not had a chance to read the explanation and am not sure what we should say on the topic but guess it's worth a mention here. Any thoughts?

**Comment by Nowosad** [comment]
Worth watching -- https://www.youtube.com/watch?v=IKM-bR6SwVs.

I think there are two things to consider:

1. Should we mention dynamic vs static CRSs somewhere (in what detail?) or is it too advanced subject matter?
2. Should we still use "EPSG:4326" for our dataset and examples or should we switch to some other CRS?

**Comment by Robinlovelace** [comment]
In think it's worth mentioning dynamic CRSs, C7 is already quite detailed and it would fit well there. I think for the moment EPSG is OK. As I see it this problem should be solved upstream. That means that computer hardware, software and systems that generate datasets with CRS metadata should move away from EPSG:4326. That will take time.

**Comment by Nowosad** [comment]
Closing for now.
