### ISSUE TITLE
Section 2.2.9 and Figure 2.11 - suggested improvement

### ISSUE THREAD

**Issue by PublicHealthDataGeek** [geocompx/geocompr#754]
FIGURE 2.11
It is a little hard to understand what the difference between these two maps are - other than a wider green line.  I d/w RL and we think adding text to the left map stating 'buffer width = 1 metre' and the right one saying 'buffer width = 1 degree longitude/latitude' helps understanding.  I wonder whether it is worth commenting the code that creates the figures too?  I have made some suggested wording below 

```
india_buffer_with_s2 = st_buffer(india, 1) # creates left map with buffer created in metres

sf_use_s2(FALSE) 
#> Spherical geometry (s2) switched off
india_buffer_without_s2 = st_buffer(india, 1) # creates right map with buffer created in degrees but this is inaccurate
#> Warning in st_buffer.sfc(st_geometry(x), dist, nQuadSegs, endCapStyle =
#> endCapStyle, : st_buffer does not correctly buffer longitude/latitude data
#> dist is assumed to be in decimal degrees (arc_degrees).
```
There is also an error in the caption wording as it references a purple polygon - but am not sure where that comes from ? earlier maps of India? 

Finally, the caption says 'resulting in a buffer with inaccurate units of degrees longitude/latitude' but the text in 2.2.9 doesnt explain why they may be inaccurate.  I think either the section text or caption text needs to make it clearer why this is the case - I can see it is in the code chunk warning and have included additional chunk comments but there is probably a better way of doing it. 

Hope this feedback is helpful

Best wishes

**Comment by Nowosad** [comment]
@Robinlovelace could you take a look at it?

**Comment by Nowosad** [comment]
Thanks @PublicHealthDataGeek -- I've tried to improve that part in https://github.com/geocompx/geocompr/commit/043d044245bd9eebd545d171b72d231855fef198.
