### ISSUE TITLE
Section on terra vector classes

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompr#780]
Similar to the sfheaders section. As discussed with @kadyb

**Comment by Robinlovelace** [comment]
Still worth doing this @kadyb? I'm thinking may make more sense to just mention it. We could also reduce the size of the substantial section on `sfheaders` and refer to a blog post to keep the coverage of classes more concise. In terms of performance I sense `geos` is just as relevant if not more so.

**Comment by Nowosad** [comment]
Hi,

1. We are (almost) not using this class in the book, so I do not think having a section for it is needed.
2. This class is already mentioned in https://r.geocompx.org/spatial-class#r-packages-for-working-with-raster-data. Also, in my work-in-progress PR, I added a footnote about how to convert between `sf` and `SpatVector`.
3. In general, I think Chapter 2 could be slightly trimmed, but @Robinlovelace I think we may be too late to make major changes.

**Comment by kadyb** [comment]
If you have deadline, I would also suggest to skip it now. In the future, we can write tutorial using the same functions in `sf`,`terra` and `geos` (like: https://geocompx.org/post/2023/ogh23/) or, the second option, is to do a summary table of the functions in these two packages (like: https://r-spatial.github.io/stars/articles/stars6.html).

**Comment by Robinlovelace** [comment]
I summary table sounds like it would be really helpful. Deadline for new features/content that I think is reasonable: end of the year, so there is a bit of time.

**Comment by Nowosad** [comment]
@kadyb I think such a blog post would be great (with table included). Feel free to start a draft if you want.
