### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by babayoshihiko** [geocompx/geocompr#812]
I have found this:
https://github.com/Robinlovelace/geocompr/releases/tag/1.1

Is anyone translating this great document? If not, I would like to so do into Japanese. I will stick to the first edition for now.

**Comment by Robinlovelace** [comment]
Hi @babayoshihiko, there were plans for a Japanese version to be created by a company back in 2019 but we have heard very little since then. Given that we're planning to complete the 2nd Edition soon (late 2022 or more likely early 2023) I would suggest that a community translation would more usefully target the 2nd edition, especially because the first part has been fully updated and will receive few updates. We will work on the other chapters over the coming months. See here for an example of a community translation, led by @defuneste: https://github.com/geocompr/fr also cc @DataMirai who is working on a Spanish translation (c3 and c4 R ready to go)!

**Comment by babayoshihiko** [comment]
@Robinlovelace, thank you for your advice. 

I have managed to translate into Japanese and build the whole book. Of course, this is still work in progress. Please check with Google translate.
http://babayoshihiko.ddns.net/geo/

Hope to keep up with French (@defuneste) and Spanish (@DataMirai).

**Comment by babayoshihiko** [comment]
May I propose a chapter on translation which can vary between languages.

In the case of Japanese, I would like to include:
* Chinese, Japanese and Korean labels do not appear especially on macOS. The solution is different for `plot` and `ggplot`.
* CRS; Japan has its own lon/lat CRC,JGD2011 and JGD200, for after/before the Great Earthquake respectively. It also has metre based projection. I understand that "language" does not refer to specifig geographic regions in many cases, but still basic CRS information is useful.
* publicly avaialble geodata.

This chapter in English may only include simple statements like "This chapter provides language-specific information." Still, the whle book chapter structure will be consistent among different languages.

**Comment by Robinlovelace** [comment]
It would be good to have that chapter, good idea @babayoshihiko. Could also be an appendix or an article / blog post but can definitely see the value. One thing to be aware of: we're still working on changes for the 2nd and 3rd parts of the book which will likely change in the next few months. After we have released the 2nd edition the book will go back into maintenance mode. Also, I've finally had a look at your work and it looks amazing, fantastic work! http://babayoshihiko.ddns.net/geo/spatial-class.html

**Comment by Robinlovelace** [comment]
Hi @babayoshihiko quick check-up on this, would you like to move your repo to our new organisation: https://github.com/geocompx

Would be great to have your translation as part of the geocompx family!

**Comment by babayoshihiko** [comment]
> Hi @babayoshihiko quick check-up on this, would you like to move your repo to our new organisation: https://github.com/geocompx
> 
> 
> 
> Would be great to have your translation as part of the geocompx family!

Of course, I am happy to be part of thr geocompx family.

What do you mean by "move my repo"? What can I do?

Currently, in my fork of grocompr, I've created 'ja' branch which has filrname-ja.Rmd files alongside the original English files.

**Comment by Robinlovelace** [comment]
The following steps should sort it:

- Rename your fork of the repo to `geocompr-ja`
- Join the geocompx org, have just sent you an invite: https://github.com/geocompx
- Transfer the repo by clicking on settings

Let us know how you get on and welcome to the family!

**Comment by Nowosad** [comment]
See https://github.com/geocompx/geocompr-ja
