### ISSUE TITLE
Ch11 

### ISSUE THREAD

**Issue by Lvulis** [geocompx/geocompr#839]
A small fix and a possible inclusion for chapter 11 - I accidentally committed the fix into #838 but perhaps can work itself into a separate PR as that one has some repetition with what @Nowosad has done already in the branch updating to **tmapv4**

- For the section on conventions one thing that naturally comes to mind when reading this is talking about a style guide such as the [tidyverse style guide](https://style.tidyverse.org/index.html) which sets out a consistent style for how code should be written. Since this book relies on tidyverse notation and functionality the tidyverse guide seems appropriate. The relevant parts of the tidyverse style guide for the target audience (introductory R and GIS users) are [section 1](https://style.tidyverse.org/files.html) and [section 2](https://style.tidyverse.org/syntax.html).
- The `code/11-x` functions are all referred to by old chapter numbers, replaced and attaching PR.

**Comment by Nowosad** [comment]
Regarding conventions -- @Robinlovelace will reply here as the primary chapter author.

@Lvulis can you prepare a separate PR for this chapter?

**Comment by Lvulis** [comment]
Sure, is the idea for the new PR to include the commit fixing the code/11-x references? I ask as I am unfamiliar with how to structure the new PR to only take the commit associated with that and not include other commits that are in #838. Would it require creating a branch just for the C11 edits? 

Not too much experience with GH for this! Sorry.

**Comment by Robinlovelace** [comment]
> Sure, is the idea for the new PR to include the commit fixing the code/11-x references?

Yes please, I looked at #838 again and see you have made some changes to Chapter 9 in that PR. It will make our life easier if you put in 2 separate PRs, one of each chapter.

**Comment by Robinlovelace** [comment]
I plan to review this chapter.

**Comment by Nowosad** [comment]
@Robinlovelace close?

**Comment by Robinlovelace** [comment]
Yep, superseded by #919
