### ISSUE TITLE
Ch9: minimal requirements for tmap4

### ISSUE THREAD

**Issue by mtennekes** [geocompx/geocompr#849]
What are the minimal requirements for the beta version of tmap4 in order to cover the new edition of your book?
As you see here https://github.com/r-tmap/tmap/issues/599, the to-do list is quite long, so I'd like to spend time on tmap efficiently. Or even better, find active co-developers who can contribute on small stand-alone issues.

**Comment by Robinlovelace** [comment]
This is a good question Martijn, thanks for asking. Jakub may be the best person to answer on the specifics but my take is pretty pragmatic: when the https://github.com/Robinlovelace/geocompr/tree/tmapv4 works with no regressions is fine for me. Perfection is the enemy of good and 'good enough for now' is my approach on this : ) 

Any way we can help you with this? Let us know, we could try to a bit of a barnstorm or an afternoon/evening/morning mini hack one day?

**Comment by mtennekes** [comment]
Fully agree. I was very ambitious with tmap4, but on the other hand I noticed that tmap3 reached a plateau.

I haven't found much time to be up-to-date with the latest developments in r-spatial, especially new packages. I wonder if they could be used in tmap. For instance, I am looking for improved algorithms for the automatic text labelling options `along.line`, `auto.placement`, and `remove.overlap`. 

Another thing I am struggling with, is an easy but elegant testing setup. I'd like to have tmap code that I can run manually and automatically. I've used testthat in the past, but not sure if that is the right approach. Currently, I have a bunch of rmd files in https://github.com/r-tmap/tmap/tree/v4/tests

**Comment by Nowosad** [comment]
The following list is probably not complete, but the important things currently are:

- [ ] - `tm_compass()` is missing
- [ ] - `tm_scale_bar()` is missing
- [ ] - `tmap_arrange()` is missing
- [ ] - `tmap_mode("view")` does not work
- [ ] - `tmap_save()` is missing
- [ ] The following code fails:

```r
nz_region = st_bbox(c(xmin = 1340000, xmax = 1450000,
                      ymin = 5130000, ymax = 5210000),
                    crs = st_crs(nz_height)) |> 
  st_as_sfc()

# fails
tm_shape(nz_elev, bbox = nz_region) +
  tm_raster()
#> SpatRaster object downsampled to 1141 by 877 cells.
#> Error in m[, 1:2, drop = FALSE]: subscript out of bounds
```

**Comment by mtennekes** [comment]
Thx @Nowosad 

* view mode is working again
* your example also works (but view mode shows world instead of nz; to be fixed)
