### ISSUE TITLE
Add <details> sections in the README?

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompr#875]
The README has got a bit long. We could use details tags.

<details>

This content is hidden by default.

</details>

Good plan? I think especially relevant to bit on reproducing the book.

**Comment by Nowosad** [comment]
Definitely. Details or Table of Contents.

**Comment by Robinlovelace** [comment]
> Definitely. Details or Table of Contents.

Great let's do it!

I'm going to mark this as good starter: if anyone wants to get involved and put in a PR, potentially their first Pull Request to this repo, this could be a good task to try (also happy to give it a bash at some point in the not-too-distant-future).
