### ISSUE TITLE
Note on 2.2.1 world plot example

### ISSUE THREAD

**Issue by bchileen** [geocompx/geocompr#924]
For context, im new to geocomp and am working my way through this great resource and am offering a perspective as a set of "fresh to geocomp" eyes.

Just a small suggestion, this issue refers to where the section references using the base r plotting function to plot the "world" dataset. While the link text directs the user to the terra::plot function, the section text states "sf objects can be plotted quickly with the base R function" which could be mistaken for using the base r::plot function instead of the terra::plot function. When I was working through the example, I found myself using the base plot function in place of terra and it may be worth explicitly stating that the plot function associated with sf is overwritten/expanded by the terra plot function.  

Also, I really appreciate your work! It has been really helpful to have such a thorough guide as a resource as someone whose transitioning from using ESRI ArcPro for geospatial to R!

**Comment by Nowosad** [comment]
Thanks @bchileen -- these links to the https://rdrr.io/cran documentation are done automatically (we do not add them). 

@Robinlovelace should we remove these automatic links? (I would probably vote yes, but I cannot find a way to do it atm).

**Comment by Robinlovelace** [comment]
Thanks for the feedback @bchileen this is a good point. The direct issue, about `plot()` being extended by **sf** is now described in these changes, see the link to the Advanced R book for details: https://github.com/geocompx/geocompr/pull/928/files

Regarding auto links to rdrr.io in the HTML, tentative :+1: from me although I think that is a separate issue. Weird that it auto links to `terra`'s plot help page, that is confusing!

**Comment by Robinlovelace** [comment]
For completeness, before:

> `sf` objects can be plotted quickly with the base R function `plot()`;
the following command creates Figure \@ref(fig:world-all).

After the change proposed in the link above:

> `sf` objects can be plotted quickly with the function `plot()`.
Although part of R's default installation (base R), `plot()` is a [*generic*](https://adv-r.hadley.nz/s3.html#s3-methods) that is extended by other packages.
**sf** contains the non-exported (hidden from users most of the time) `plot.sf()` function which is what is called behind the scenes in the following command, which creates Figure \@ref(fig:world-all).

**Comment by bchileen** [comment]
Thanks for adding the extra clarification!

**Comment by Robinlovelace** [comment]
No problem, any further issues or potential to improve the wording let us know!

**Comment by Robinlovelace** [comment]
Regarding the wider issue with autolinking, I've opened an issue here: https://github.com/rstudio/bookdown/issues/1406

**Comment by Robinlovelace** [comment]
> Thanks @bchileen -- these links to the https://rdrr.io/cran documentation are done automatically (we do not add them).
> 
> @Robinlovelace should we remove these automatic links? (I would probably vote yes, but I cannot find a way to do it atm).

One more thought on this: instead of removing them we can do:

```
[`plot(...)`](link/to/docs)
```

To override the defaults.
