### ISSUE TITLE
prediction on a resample object

### ISSUE THREAD

**Issue by selvaje** [geocompx/geocompr#925]
Hi, 
thanks a lot for the very interesting and clear book. 
I need some clarification concerning a following step after a resampling CV. 

I'm searching from already few days how to predict on an external data using a resampled object. 
In particular I'm referring to the  line 403 & 416

`
resampling = mlr3::rsmp("repeated_spcv_coords", folds = 5, repeats = 100)
rr_spcv_glm = mlr3::resample(task = task,
                                                      learner = learner,
                                                      resampling = resampling,
                                                      store_models = TRUE )
`

By adding the `store_models = TRUE`  it is possible to store all the 500 learners outputs and check each single performance and prediction.  
It also possible to check the "average" score 
`  rr_spcv_glm$aggregate() `
or the "average" prediction
`  rr_spcv_glm$prediction() `

Is there is a way to "merge/aggregate" the models and be able to predict to a raster dataset? something similar to: 

`
pred = terra::predict(stack-raster , model = rr_spcv_glm-merged, fun = predict ) 
`

In my case I have implemented a spatial CV in a learner-ranger (everything is clear) but I miss how to predict the spatial-CV-model in to the raster. 

Thanks in advance 
Giuseppe Amatulli

**Comment by selvaje** [comment]
Hi 
thanks for the interesting and clear book. 
I'm writing concerning a following step to perform a prediction from a resample spatial-CV object.  In particular i'm referring to line 413 & 416

`
resampling = mlr3::rsmp("repeated_spcv_coords", folds = 5, repeats = 100)
rr_spcv_glm = mlr3::resample(task = task,
                             learner = learner,
                             resampling = resampling,
                             store_models = TRUE)
`

by adding the `store_models = TRUE` it is possible to retrieve the performance of each sub-model, and by `rr_spcv_glm$aggregate()` it possible to get the overall error score. 

Is there a way "merge/aggregate" all 500 models in such a way that it is possible to make a prediction on raster dataset? Something like 

`
raster_prediction = terra::predict(raster_stack,  model = rr_spcv_glm_merged ,  fun = predict )
`
Hope that my question is clear. 
Thanks in advance 
Giuseppe Amatulli

**Comment by jannes-m** [comment]
We are doing performance estimation here, not prediction. For the latter pls refer to Chapter 14 Ecology.

**Comment by Nowosad** [comment]
@jannes-m -- maybe it would be worth to add a paragraph about prediction in the 12 chapter as well? I got that question a few times already...

**Comment by jannes-m** [comment]
Yep, maybe you are right. Though we are saying that this chapter is not about prediction, it does not seem to be clear enough. So we could emphasize this even more and maybe also leave out the glm prediction as this might raise false expectations.

**Comment by jannes-m** [comment]
OK, I noted this in my to do list and will come up with something.

**Comment by selvaje** [comment]
Thanks Jannes and Jakub, 
yes it is clear that the chapter focus  on performance estimation and not on prediction. Anyway should be nice to see few line how to do a prediction from a CV implementation. 

Nonetheless, I think I have an idea by accessing the sub-models and make a prediction for each of them, then merge the prediction. Anyway should be nice to have an example. 
Thanks for the support 
Giuseppe

**Comment by jannes-m** [comment]
No, this is exactly what you shouldn't do. Again, please refer to Chapter 14 how do do predictions properly.
