### ISSUE TITLE
New shiny references

### ISSUE THREAD

**Issue by Nowosad** [geocompx/geocompr#931]
@Robinlovelace -- see the bottom of the https://r.geocompx.org/adv-map.html#interactive-maps section. 

Also -- maybe it would be good to mention a shiny resource or two here (e.g., https://mastering-shiny.org/, https://unleash-shiny.rinterface.com/, and https://engineering-shiny.org/)?

**Comment by Robinlovelace** [comment]
Just mentioned the more popular Mastering Shiny reference which should be more than enough, although probably also worth adding a link to the book's URL.
