### ISSUE TITLE
2.3.1 small typo (missing s)

### ISSUE THREAD

**Issue by cc50liu** [geocompx/geocompr#944]
In [section 2.3.1](https://r.geocompx.org/spatial-class.html#r-packages-for-working-with-raster-data), this sentence is missing the s I put in bold and capital below.

> "until the development of terra and stars. Both more recently developed package**S** provide powerful and performant functions for working with raster datasets and there is substantial overlap between their possible use cases."

**Comment by Nowosad** [comment]
Thank you @cc50liu
