### ISSUE TITLE
Small typo in section 2.9

### ISSUE THREAD

**Issue by cc50liu** [geocompx/geocompr#945]
In the last paragraph (within blue box) of [section 2.9](https://r.geocompx.org/spatial-class.html#s2) there's an extra D (shown in bold and capital below).
> Although the sf’s use**D** of S2 makes sense in many cases, in some cases there are good reasons for turning S2 off for the duration of an R session or even for an entire project.

**Comment by Nowosad** [comment]
Thanks @cc50liu!
