### ISSUE TITLE
Consider setting explicit plot margins for figure 2.1.5 code. 

### ISSUE THREAD

**Issue by cc50liu** [geocompx/geocompr#946]
When I run the `plot(my_rast)` code at the top of [section 2.3.3](https://r.geocompx.org/spatial-class.html#basic-map-raster) after working through previous examples in the chapter, I receive 
`Error in plot.new() : figure margins too large`
To avoid this, could that section of code explicitly set the needed margins?

**Comment by Nowosad** [comment]
I assume that you are using RStudio -- this error happens when your plot panel is too small for the figure. Try to make the plot panel larger and then run the plot function again.

**Comment by cc50liu** [comment]
Yes, I'm in RStudio.  I tried making the plot panel as large as possible on my laptop, but still received the same error.  I'll just skip over this part and keep reading the book.  Here's a screenshot of what I see:
![image](https://user-images.githubusercontent.com/101796166/230366736-3ca21b7f-0614-4691-9e1a-096e7838d9cb.png)

**Comment by Nowosad** [comment]
You may try to restart your graphic device and make the plot again:

```r
dev.off()
plot(my_rast)
```

**Comment by cc50liu** [comment]
That solved the problem!  Thanks!
