### ISSUE TITLE
QGIS Docker image failing

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompr#948]
With this error message: 

```
> library(sf)          # classes and functions for vector data
Error: package or namespace load failed for ‘sf’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/sf/libs/sf.so':
  libproj.so.22: cannot open shared object file: No such file or directory
```

As shown in screenshot below running the `qgis` branch in a local devcontainer. Solution is going to be in https://github.com/geocompx/docker and will involved reinstalling `sf` I guess. Documenting here for now...

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/230739457-d6897e09-391f-4af3-893e-a47dedda8118.png)

**Comment by Robinlovelace** [comment]
Giving reinstalling `sf` a go:

![image](https://user-images.githubusercontent.com/1825120/230739516-54ad804b-8fae-4c8b-ac40-840dc30e561f.png)

**Comment by Robinlovelace** [comment]
The problem with `install.packages("sf")` is that it's configured to install binary packages which are not right here:

```
> install.packages("sf")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://packagemanager.posit.co/cran/__linux__/jammy/latest/src/contrib/sf_1.0-12.tar.gz'
Content type 'binary/octet-stream' length 3498486 bytes (3.3 MB)
```

**Comment by Robinlovelace** [comment]
Update: `library(sf)` fails even after it's been reinstalled from GitHub:

```
library(sf)          # classes and functions for vector data
Error: package or namespace load failed for ‘sf’ in get(Info[i, 1], envir = env):
 lazy-load database '/usr/local/lib/R/site-library/sf/R/sf.rdb' is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1
```

Any ideas @jannes-m or anyone?
To reproduce this try

```
gh repo clone geocompx/geocompr
cd geocompr
git checkout qgis
code .
```

Then open in devcontainer.

**Comment by Robinlovelace** [comment]
Update: OK I think reinstalling it and re-compiling worked, in a new terminal I get

```
library(sf)
Linking to GEOS 3.11.1, GDAL 3.6.2, PROJ 9.1.1; sf_use_s2() is TRUE
```

**Comment by Robinlovelace** [comment]
Seems to be good with https://github.com/geocompx/docker/commit/6912327fa2ae07ac331028138787e06ec88824a0

Tested building it locally. 
I get this:

```
> library(qgisprocess)
QGIS version: 3.30.1-'s-Hertogenbosch
Having access to 349 algorithms from 4 QGIS processing providers.
Run `qgis_configure(use_cached_data = TRUE)` to reload cache and get more details.
>>> Run `qgis_enable_plugins()` to enable 3 disabled plugin(s) and
    access their algorithms: grassprovider, otbprovider,
    processing_saga_nextgen
```

**Comment by Robinlovelace** [comment]
Getting close but now hitting this:

```
Run `qgis_algorithms()` for a list of available algorithms.
Backtrace:
 1. qgisprocess::qgis_show_help("saga:sagawetnessindex")
 3. qgisprocess:::qgis_help_text(algorithm)
 4. qgisprocess::assert_qgis_algorithm(algorithm)
```

**Comment by Robinlovelace** [comment]
Seems it's in there:

```
> grep("wetness", qgis_algo$algorithm, value = TRUE)
[1] "sagang:sagawetnessindex"              
[2] "sagang:topographicwetnessindexonestep"
[3] "sagang:topographicwetnessindextwi"    
[4] "sagang:wetness"                       
> #> [1] "saga:sagawetnessindex"           "saga:topographicwetnessindextwi"
```
But the name has changed.

**Comment by jannes-m** [comment]
You need to install from source. The same goes for terra and of course all other packages linking to gdal, etc. So far I haven't found an easier way to update the linking.

**Comment by jannes-m** [comment]
You need to install from source. The same goes for terra and of course all other packages linking to gdal, etc. So far I haven't found an easier way to update the linking. And yes, we are now using sagang, i.e. the Saga New generation plugin.

**Comment by jannes-m** [comment]
To enable the plug-ins, use `qgis_enable_plugins(c(name_of_the_plugins))`.

**Comment by jannes-m** [comment]
It was on my to-do list to update the gis chapter and the Dockerfile accordingly. Not sure when I can do so because we are on vacation right now but probably within the next couple of days.

**Comment by Robinlovelace** [comment]
> It was on my to-do list to update the gis chapter and the Dockerfile accordingly. Not sure when I can do so because we are on vacation right now but probably within the next couple of days.

No rush, enjoy the holidays! Good news here: the qgis image is working perfectly and I have got the qgis actions working. Any review comments/changes to https://github.com/geocompx/geocompr/pull/751 v. welcome, will be great to get this merged and tested on the updated `qgis` image with every commit.
