### ISSUE TITLE
Error when running rasterize code in 6.4

### ISSUE THREAD

**Issue by cc50liu** [geocompx/geocompr#951]
[Section 6.4](https://r.geocompx.org/raster-vector.html#rasterization) recommends running this code:

`ch_raster2 = rasterize(cycle_hire_osm_projected, raster_template, 
                       fun = "length")`

When I run it, I receive this error:
`Error in FUN(X[[i]], ...) : 
  2 arguments passed to 'length' which requires 1`

**Comment by Robinlovelace** [comment]
Thanks for opening the issue @cc50liu. Which version of `terra` are you running?

**Comment by Robinlovelace** [comment]
It looks like the issue was fixed upsteam in the `terra` package, which was updated on CRAN yesterday: https://github.com/rspatial/terra/issues/1054

https://cran.r-project.org/web/packages/terra/index.html

Which says:

```
Published: | 2023-04-08
```

**Comment by cc50liu** [comment]
Thanks for researching the issue @Robinlovelace.  I just installed the updated `terra` version and now don't have the problem.  I appreciate your help.

**Comment by Robinlovelace** [comment]
Great to hear! Any other comments/suggests/issues in the book do let us know, the content is so much better thanks to the amazing communities that have emerged around open source projects :rocket:
