### ISSUE TITLE
Error in Chapter 14 in workflow testing dev versions

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompr#956]
Just spotted this issue:

```
Quitting from lines 407-425 (14-location.Rmd) 
Error in .rawTransform(projfrom, projto, xy) : 
  no slot of name "ptr" for this object of class "SpatVector"
Calls: local ... .getSRS -> <Anonymous> -> <Anonymous> -> .rawTransform
Execution halted
  |..................................................  |  97% (bikeshop-berlin)
```

Any ideas? Source: https://github.com/geocompx/geocompr/actions/runs/4690500051/jobs/8313670612#step:4:3613

I have no idea of the cause let alone possible solutions.

**Comment by Nowosad** [comment]
I think this was an issue in terra, but is now fixed (however, I am not sure if it is fixed on CRAN or dev...)
