### ISSUE TITLE
Add exercises in chapter 11

### ISSUE THREAD

**Issue by Nowosad** [geocompx/geocompr#959]
https://github.com/geocompx/geocompr/blob/main/_11-ex.Rmd

**Comment by Robinlovelace** [comment]
@Nowosad just looking at that file now, which bits specifically need updating? Looking at https://r.geocompx.org/solutions/ I can see that the solutions are not present where they should be but not sure how to make them appear after an initial glance.

**Comment by Nowosad** [comment]
You need to update the https://github.com/geocompx/geocompr/blob/main/_11-ex.Rmd file. Currently, it has only exercises, but no solutions. When you add the solutions (see other `-ex.Rmd` files), then I will add it to the rendering list at https://r.geocompx.org/solutions/

**Comment by Robinlovelace** [comment]
Makes sense. There are already some solutions, e.g.

https://github.com/geocompx/geocompr/blob/6f140bb78d435cfb05fc0d4721e0c52257ebb297/_11-ex.Rmd#L16-L22

Looking at other examples now to add the text to the solutions...
