### ISSUE TITLE
Check dependency checks 

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompr#965]
The check for SAGA here always returns false according to comments on https://github.com/geocompx/geocompr/commit/3ed05da71d65915d790f8600fd832eaa361b63c2:

https://github.com/geocompx/geocompr/blob/3ed05da71d65915d790f8600fd832eaa361b63c2/10-gis.Rmd#L24-L37

Related: https://github.com/geocompx/geocompr/commit/0a58256f5230359fce0cb30c7ed2811f4e7bf582 and https://github.com/geocompx/docker/issues/37

**Comment by Robinlovelace** [comment]
Checking this by running the following line:

https://github.com/geocompx/geocompr/blob/f5a5c4e69f7a152f547bbca5333e92b45149ce2d/10-gis.Rmd#L140

**Comment by Robinlovelace** [comment]
That generates this: 

![image](https://github.com/geocompx/geocompr/assets/1825120/384cbec8-490f-4a56-b6cb-204368eebf53)

**Comment by Robinlovelace** [comment]
Issue with the container: 

``` r
qgisprocess::qgis_providers()
#> Attempting to load the cache ... Success!
#> # A tibble: 4 × 3
#>   provider provider_title    algorithm_count
#>   <chr>    <chr>                       <int>
#> 1 gdal     GDAL                           56
#> 2 qgis     QGIS                           50
#> 3 3d       QGIS (3D)                       1
#> 4 native   QGIS (native c++)             242
```

<sup>Created on 2023-05-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Robinlovelace** [comment]
So more motivation to address this: https://github.com/geocompx/docker/issues/37

Can you take a look please Jannes?

**Comment by jannes-m** [comment]
Yes, let me do it 😊

**Comment by jannes-m** [comment]
but I just checked it is not an issue with the container, in essence we have to use `qgis_plugins()` for checking and later on in the text (before calling `qgis_providers()`) we have to enable the plugins. But I will add this and an appropriate description in the text. I hope to do so this evening/night.

**Comment by Robinlovelace** [comment]
Thanks Jannes, makes sense. I was getting confused between `qgis_plugins()` and `qgis_providers()` I think. Updated reprex showing that SAGA and GRASS are in there:

``` r
# Only run code if qgis is installed
 has_qgis_plugins = FALSE 
 # Check to see that the qgisprocess package is installed: 
 if ("qgisprocess" %in% installed.packages()) { 
   # Check that QGIS is available to prevent errors in subsequent checks: 
   if (qgisprocess::has_qgis()) { 
     plugins = qgisprocess::qgis_plugins()
     message(paste0(plugins$name, collapse = ", "))
     # Check that the plugins are installed (they will loaded later): 
     has_grass = qgisprocess::qgis_has_provider("grass7") 
     message("has_grass: ", has_grass)
     has_saga = qgisprocess::qgis_has_provider("sagang") 
     message("has_saga: ", has_saga)
     has_qgis_plugins = has_grass && has_saga 
   } 
 }
#> Attempting to load the cache ... Success!
#> grassprovider, otbprovider, processing, processing_saga_nextgen
#> has_grass: FALSE
#> has_saga: FALSE
```

<sup>Created on 2023-05-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
