### ISSUE TITLE
Point order in a polygon in chapter 11

### ISSUE THREAD

**Issue by Nowosad** [geocompx/geocompr#970]
@Robinlovelace, the convention is that the points building the polygon should be ordered counter-clockwise (see, for example, the last paragraph in https://r-spatial.org/book/03-Geometries.html#sec-valid).

That is not the case in chapter 11 (https://r.geocompx.org/algorithms.html), where the points are ordered clockwise. It is not a big problem, but I think it would be better to improve it (give "a good example" for others).

**Comment by Robinlovelace** [comment]
Good point Jakub, will look to fix this.
