### ISSUE TITLE
cppRouting update

### ISSUE THREAD

**Issue by vlarmet** [geocompx/geocompr#974]
Hi,

Thank you for your this great book !
FYI, the new release of cppRouting implements algorithms for solving the Traffic Assignment Problem (Frank Wolfe algorithm and variants, algorithm B from Robert Dial).

**Comment by Robinlovelace** [comment]
Great stuff, thanks @vlarmet and great work with implementing contraction hierarchies in C++ + R! Are you happy to put in a PR with a few words on this?

**Comment by vlarmet** [comment]
Of course, I'll do that in the next few weeks.

**Comment by vlarmet** [comment]
I think I should edit transport.Rmd.
I can talk about traffic assignment, and contraction hierarchies as well.
Do you think these topics need the creation of new sections ?

**Comment by Robinlovelace** [comment]
It's worth mentioning contraction hierarchies and traffic I think. The former can lead to much more efficient route calculation (out of interest would be be interested in benchmarking your C++ code with the Rust crate `fast_paths`? cc @dabreegster on that, the more info we have on different open routing options the better for everyone in this space is my thinking). The latter is important to real world transport modelling. My request if you do want to add some more words on these things, please don't add too many, it's already a long chapter. Suggestions of words we can remove also welcome. Many thanks!

**Comment by vlarmet** [comment]
I have done some benchmark yesterday on my machine. 
Test networks are from DIMACS challenge : 

- New York : 264.347 nodes, 730.100 edges
- California : 1.890.816 nodes,  4.630.444 edges
- USA : 23.947.348 nodes, 57.708.624 edges

Query time is averaged through 100.000 random origin-destination pairs.
`fast_paths` seems to be faster for preprocessing but is slower for querying. Preprocessing seems to be less stable in `fast_paths` (maybe due to initial node ordering ?), regarding USA distance.  

Nevertheless, there is an important difference : network weights are in **double precision** in `cppRouting` while `fast_paths` only accepts  **unsigned integers**. This is why preprocessing is faster in the latter, but it is in my opinion a true limitation in solving real world problems.

![image](https://github.com/geocompx/geocompr/assets/48824420/fdd2ea98-5060-4197-b6e4-00387480a206)

**Comment by dabreegster** [comment]
@easbar as FYI on the new benchmark

> network weights are in double precision in cppRouting while fast_paths only accepts unsigned integers

I don't recall the conversation about this initially, but I'm pretty sure uints are a deliberate choice in `fast_paths`. They force the user to think about the precision they need for time / distance / cost units. In my [traffic simulation application](https://github.com/a-b-street/abstreet/), this has worked just fine; precision lower than a centimeter or millisecond isn't relevant for routing.

**Comment by easbar** [comment]
@dabreegster thanks for the pointer

> I don't recall the conversation about this initially, but I'm pretty sure uints are a deliberate choice in fast_paths. They force the user to think about the precision they need for time / distance / cost units. In my [traffic simulation application](https://github.com/a-b-street/abstreet/), this has worked just fine; precision lower than a centimeter or millisecond isn't relevant for routing

Yes, exactly. Using floating point number can lead to various problem where an exact comparison is needed, for example when using beeline distances or similar. At the same time they force users of the library to think about the units of their weights. 

> network weights are in double precision in cppRouting while fast_paths only accepts unsigned integers. This is why preprocessing is faster in the latter, but it is in my opinion a true limitation in solving real world problems.

I'm not sure if using unsigned integers for the weights is really the reason for a faster preprocessing here, or if makes a distance at all. If I'm not mistaken fast_paths could quite easily be adapted to using another datatype for the edge weights, i.e. I don't think the algorithm makes any important assumptions about the weight datatype.

> Query time is averaged through 100.000 random origin-destination pairs.
fast_paths seems to be faster for preprocessing but is slower for querying.

Thanks for the benchmark! Note that there typically is a trade-off between preprocessing and querying time, i.e. using some of fast_path's parameters it should be possible to reduce the query time at the cost of a slower preprocessing.

> Preprocessing seems to be less stable in fast_paths (maybe due to initial node ordering ?), regarding USA distance.

Yes the numbers for USA distance look interesting indeed. 

When I did a [performance check on the same (?) dataset](https://github.com/easbar/fast_paths/#benchmarks) I measured 588s preparation for the time metric and 1020s for the distance metric, compared to the 276s/6600s you measured here? The difference could be due to a different choice of the parameters(?).

**Comment by vlarmet** [comment]
`cppRouting` need double precision because derivatives are computed during estimation of traffic equilibrium (cost depend of flow because of congestion).  

> When I did a [performance check on the same (?) dataset](https://github.com/easbar/fast_paths/#benchmarks) I measured 588s preparation for the time metric and 1020s for the distance metric, compared to the 276s/6600s you measured here? The difference could be due to a different choice of the parameters(?).

As a quick test, I have just edited `lib.rs` file by pointing to network paths. 
I have not changed any parameters : 
```
    #[test]
    fn run_performance_test_dist() {
        println!("Running performance test for USA time");
        // road network extracted from OSM data from Bremen, Germany using the road distance as weight
        // prep: 190ms, query: 16μs, out: 68494, in: 68426
        // todo: try to tune parameters
        run_performance_test(
            &InputGraph::from_file("meta/test_maps/USA-road-t.USA.gr"),
            &Params::new(0.1, 500, 2, 50),
            845493338,
            30265,
        )
    }

    #[ignore]
    #[test]
    fn run_performance_test_time() {
        println!("Running performance test for USA dist");
        // road network extracted from OSM data from Bremen, Germany using the travel time as weight
        // prep: 256ms, query: 11μs, out: 64825, in: 65027
        // todo: try to tune parameters
        run_performance_test(
            &InputGraph::from_file("meta/test_maps/USA-road-d.USA.gr"),
            &Params::new(0.1, 100, 2, 100),
            88104267255,
            30265,
        );
    }
```

Maybe I should ?  

Your benchmark show similar preprocessing time to `cppRouting`.

**Comment by easbar** [comment]
> Maybe I should ?

Yes, for benchmarking maybe better use the defaults, i.e. `&Params::default()` unless you want to do something special.
Currently they are `Params::new(0.1, 500, 100, 500)` which could explain the different results.

**Comment by dabreegster** [comment]
For any benchmarks, shouldn't there be a script or clear set of reproducible instructions documented, so somebody on a different machine can repeat?

**Comment by easbar** [comment]
Yes, I agree :) I'll add a script for this. 

Btw for the very interested there is some discussion about the parameter choices here: https://github.com/easbar/fast_paths/pull/37

**Comment by vlarmet** [comment]
Ok thank you! I will update benchmark results with default parameters

**Comment by vlarmet** [comment]
Benchmark results with default parameters : 

![image](https://github.com/geocompx/geocompr/assets/48824420/5a0cc578-fad6-4fd4-8666-467aa2f92f30)

**Comment by Robinlovelace** [comment]
Impressive. Is there are reproducible example to try this at home? Need for routingBenchmark repo IMO.

**Comment by easbar** [comment]
@vlarmet Thanks for the benchmarks again. 
@Robinlovelace For fast_paths you can run this code: https://github.com/easbar/fast_paths/blob/26783eb813c5f8e706ec8a79580b8188ea9c7e4c/src/lib.rs#L510-L534

**Comment by Robinlovelace** [comment]
Great to see these reproducible examples (affectionately known as reprexes  : ) will aim to give them a spin!

**Comment by Robinlovelace** [comment]
Hi @vlarmet we're trying to bring everything together before end of 2023. Do you still want to contribute some code to the transport chapter? Now an ideal time to do so, realise this thread has gone a bit off topic, but is very interesting and of use to many so hope we can integrate your code in Geocomputation with R.

**Comment by vlarmet** [comment]
hi @Robinlovelace yes of course, I'll try to find a time to do it in the coming days

**Comment by Robinlovelace** [comment]
Many thanks Vincent!

**Comment by Robinlovelace** [comment]
Massive thanks @vlarmet! Please see the commits above for post merge changes. I've now referenced Wardrop (1952), which seems like a seminal paper in the field. As you'll see I've merged your 2 bits into the routing section. Although assignment does fit into networks I put them both in one place as they're related and want to keep it simple.
