### ISSUE TITLE
Book cover competition II

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompr#980]
Following https://github.com/geocompx/geocompr/issues/284 we're organising a book competition. Front cover ideas welcome in the comments below, via social media (please tag Robin or Jakub on Twitter or Mastodon), or via email TBC.

**Comment by Robinlovelace** [comment]
https://github.com/geocompx/geocompx.org/pull/15#pullrequestreview-1749218909

**Comment by Robinlovelace** [comment]
https://github.com/geocompx/geocompx.org/pull/15

**Comment by Robinlovelace** [comment]
Info on how to submit. Questions/ideas/submissions: welcome! https://geocompx.org/post/2023/map-cover-competition/

**Comment by Jorget778** [comment]
Hello, I have an idea for the cover of the book, but I want to know if it should have a code? Greetings

**Comment by Nowosad** [comment]
Hi @Jorget778 -- yes, having a code implementing the idea is preferable

**Comment by Robinlovelace** [comment]
And the winner is.. drum roll, @BjnNowak:

https://github.com/BjnNowak/geocomputation/

Great job on the submission, we have some ideas on tweaking it before it goes into production, but overall: it's a winner, thanks for the submission. @cj-holmes we liked your idea also. Please send us your address in a private message on Discord or by other means and we'll ensure you get sent the prizes thanks to Taylor and Francis.

**Comment by cj-holmes** [comment]
> And the winner is.. drum roll, @BjnNowak:
> 
> https://github.com/BjnNowak/geocomputation/
> 
> Great job on the submission, we have some ideas on tweaking it before it goes into production, but overall: it's a winner, thanks for the submission. @cj-holmes we liked your idea also. Please send us your address in a private message on [Discord](https://discord.gg/PMztXYgNxp) or by other means and we'll ensure you get sent the prizes thanks to Taylor and Francis.

Thanks @Robinlovelace, Is there an email address I can send my postal address to?

**Comment by Robinlovelace** [comment]
Hey @cj-holmes sure, you can email me at rob00x at gmail.com.
