### ISSUE TITLE
Update citations: use year not date fields

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompr#986]

**Comment by Nowosad** [comment]
Great work @Robinlovelace: in short, Zotero can export to .bib as Better BibLaTeX or as Better BibTeX (I am often confused by it..). Which one should we use? Maybe you can add a line about it to this repo README?

**Comment by Nowosad** [comment]
Currently, many references are broken (due to changed keys?), e.g., https://r.geocompx.org/intro#the-history-of-r-spatial

**Comment by Robinlovelace** [comment]
Woops. Looks like the export settings are right. Will take a look.

![image](https://github.com/geocompx/geocompr/assets/1825120/27871a74-b1ae-4f2c-a248-504ce93f9067)

**Comment by Robinlovelace** [comment]
Faulty one for first I've found, guess I just need to update the keys:

https://github.com/geocompx/geocompr/blob/5c800850d68e24ec05918104dcc269df601a68ef/geocompr.bib#L196
