### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompr#988]
The link on this line seems broken:

 https://github.com/geocompx/geocompr/blob/40e6a4971cbc112e044c76237a707b0dd6010bea/12-spatial-cv.Rmd#L489

https://mlr3book.mlr-org.com/technical.html#fallback-learners

Any ideas @jannes-m ?

**Comment by jannes-m** [comment]
seems that urls have changed again, will fix them now

**Comment by jannes-m** [comment]
Closed via 9d98989.

**Comment by jannes-m** [comment]
will check now also links in chapter 15

**Comment by jannes-m** [comment]
ok, also fixed. Thanks for the nudge @Robinlovelace !
