### ISSUE TITLE
Fix urls

### ISSUE THREAD

**Issue by Nowosad** [geocompx/geocompr#991]
Thanks to the great work of @nanxstats at https://nanx.me/blog/post/rmarkdown-quarto-link-checker/, I was able to check and fix many broken urls in our book (see https://github.com/geocompx/geocompr/pull/990). There are still some issues left, so @Robinlovelace  and @jannes-m please take a look at the remaining broken urls and update them.

Chapter 1:

- [x] http://digitallibrary.hsp.org/index.php/Detail/Object/Show/object_id/9285
- [x] http://spatial.nhh.no/meetings/vienna/index.html
- [x] http://www.geocomputation.org/2000/GC009/Gc009.htm

Chapter 7:

- [x] https://www.iogp.org/our-committees/geomatics/

Chapter 11:

- [x] https://github.com/libgeos/geos/search?q=getCentroid

Chapter 12:

- [x] https://mlr-org.github.io/mlr-tutorial/release/html/
- [x] https://mlr3book.mlr-org.com/optimization.html
- [x] https://mlr3book.mlr-org.com/spatiotemporal.html
- [x] https://mlr3book.mlr-org.com/technical.html#fallback-learners

Chapter 13:

- [x] https://atfutures.github.io/dodgr/
- [x] https://www.sciencedirect.com/science/article/pii/S0967070X21003401

Chapter 14:

- [x] http://inspire-geoportal.ec.europa.eu/discovery/

Chapter 14 (exercises):

- [x] https://www.zensus2011.de/SharedDocs/Downloads/DE/Pressemitteilung/DemografischeGrunddaten/csv_Bevoelkerung_100m_Gitter.zip?__blob=publicationFile&v=3
- [x] https://www.zensus2011.de/SharedDocs/Downloads/DE/Pressemitteilung/

Chapter 15:

- [x] https://mlr-org.github.io/interpretable-machine-learning-iml-and-mlr/

Chapter 16:

- [x] https://moc.online.uni-marburg.de/doku.php

Index.Rmd:

- [x] Twitter links -- we mention twitter a few times there... Maybe we could replace these mentions with mastodon?

README:

- [x] https://www.rocker-project.org/use/managing_users/

**Comment by jannes-m** [comment]
exercise links of chapter 14 are still working, so I haven't changed them. Otherwise, thanks a lot for checking all the urls of the book, @Nowosad!
