### ISSUE TITLE
Robin: second edition

### ISSUE THREAD

**Issue by Nowosad** [geocompx/geocompr#995]
The below comments are based on my read of the whole book. Feel free to ignore the ones you think are not useful:

General:

- [x] 1. Are we still using the [Dockerfile](https://github.com/geocompx/geocompr/blob/main/Dockerfile) or can we remove it?

Chapter 1:
- [x] 1. "An autonomous vehicle, for example, can generate 100 GB of data per day [@theeconomist_autonomous_2016]." Based on my quick search -- this number is rather outdated
- [x] 2. Are those still the best examples: "Furthermore, many map server applications use Java\index{Java} including Geoserver/Geonode, deegree and 52°North WPS."?

Chapter 4:
- [x] 1. DE-9IM strings: there should be an explanation that it only works properly of PCRSs
- [x] 2. Why the Distance relations section is the last in the vector part? Should not it be earlier, as it explains "relations"?

Chapter 8:
- [x] 1. "An example is the **geojsonsf** package." -- is this still the best example (the benchmark is 5 years old)

Chapter 11:
- [x] 1. landau_targets_2021 -- the reference should be fixed
- [x] 2. "Such dependencies should be mentioned" -- maybe that would be a good place to mention renv? 
- [ ] 4. The end of Functions sections, you show how to have an sf output, but maybe it would be also good to show how to improve this function to have `sf` as an input?

Chapter 16:
1. There are many broken references in that chapter.

**Comment by Robinlovelace** [comment]
Great set of comments @Nowosad. Will act on these by end of the year.

**Comment by Robinlovelace** [comment]
>  2. Are those still the best examples: "Furthermore, many map server applications use Java\index{Java} including Geoserver/Geonode, deegree and 52°North WPS."?

I've completely removed the bit on Java in Chapter 1 in #1023, it adds little to what is already quite a long chapter.

**Comment by Robinlovelace** [comment]
Regarding

>  4. The end of Functions sections, you show how to have an sf output, but maybe it would be also good to show how to improve this function to have sf as an input?

I don't think that is necessary as it's an exercise (E4).
