### ISSUE TITLE
Jannes: second edition

### ISSUE THREAD

**Issue by Nowosad** [geocompx/geocompr#996]
The comments below are based on my reading of the whole book. Feel free to ignore the ones you think are not useful:

Chapter 4:
- [x] "To do so, we can weight the distance with elevation so that each additional altitudinal meter ‘prolongs’ the Euclidean distance" -- can you add a sample code for this (e.g., using the `nz_elev` data)? 

Chapter 12:
- [x] Maybe it would be a good idea to add comments to the packages attached at the start of the chapter (v. shortly what do they do)
- [x]  I think we discussed that in the past: I think it would be good to add a note at the end of the chapter about how to make spatial predictions from mlr3 model. I got a question about this a few times.
 
Chapter 14:
- [x] "which tries repeatedly (three times in this case) to download the data". Based on the code, is it not two times?

Chapter 15: 
- [x] Chapters 13 and 14 both have similar lists at the beginning, explaining the rest of the chapter and giving cross-references to all of the sections in these chapters (see https://r.geocompx.org/transport#introduction-7 and https://r.geocompx.org/location#case-study. I think it would be nice to have such a list in Chapter 15.

**Comment by jannes-m** [comment]
Thanks for the suggestions @Nowosad, these are very much appreciated and I will take care of them.

**Comment by jannes-m** [comment]
Yes, I will take care of these this week! And I think in chapter 12 we already tell the reader to look at c15 for instructions how to do spatial predictions but maybe we have to emphasize this even more or so say so in the beginning of the chapter.

**Comment by Robinlovelace** [comment]
Big thumbs up to that, thanks Jannes!

**Comment by jannes-m** [comment]
@Nowosad you are absolutely right with regard to the `while` loop iterations. I was counting also the first try outside of the while loop but yes, as it stands, it was simply wrong. Hence, I have updated the text accordingly. Thanks for spotting!

**Comment by jannes-m** [comment]
@Nowosad Regarding the computation of raster distance weighted by some other variable, I have pointed the reader to E8 and E9 at the end of chapter 4 where we are doing exactly this.

**Comment by Nowosad** [comment]
#1054
