### ISSUE TITLE
Possible issue in the Introduction regarding a reference

### ISSUE THREAD

**Issue by tibbles-and-tribbles** [geocompx/geocompr#999]
From the Introduction (https://r.geocompx.org/intro), the sentence “Interfaces to other software are part of R” ([Eddelbuettel and Balamuta 2018](https://r.geocompx.org/references#ref-eddelbuettel_extending_2018)) is problematic. Here's the surrounding context...

> This book is also motivated by the importance of reproducibility for scientific research. It aims to make reproducible geographic data analysis workflows more accessible, and demonstrate the power of open geospatial software available from the command-line. “Interfaces to other software are part of R” ([Eddelbuettel and Balamuta 2018](https://r.geocompx.org/references#ref-eddelbuettel_extending_2018)). This means that in addition to outstanding ‘in house’ capabilities, R allows access to many other spatial software libraries, explained in Section [1.2](https://r.geocompx.org/intro#why-use-r-for-geocomputation) and demonstrated in Chapter [10](https://r.geocompx.org/gis#gis). Before going into the details of the software, however, it is worth taking a step back and thinking about what we mean by geocomputation.

I'm not sure how to unpack this issue, but I can say that "Interfaces to other software are part of R" is not under References at the end of the chapter. 

I hope this is useful!

**Comment by Robinlovelace** [comment]
That is useful. Will take a look, let us know of any other issues as you find them!

**Comment by Nowosad** [comment]
I can see it in the references --- https://r.geocompx.org/references#ref-eddelbuettel_extending_2018

**Comment by Nowosad** [comment]
Oh, I see. Thanks for the explanation @tibbles-and-tribbles
